#!/usr/bin/env node
// Generates src/inline.mjs: the "./inline" export target — the wasm-bindgen
// web build with its .wasm module embedded as a base64 string, for
// bundler-hostile environments that can't resolve a sibling .wasm asset
// (ARCHITECTURE.md JS/TS packaging: "optional base64-inlined entry"). Run
// by `just build-wasm` and by the npm `prepack` hook; keep this simple.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(here, "..", "wasm", "web", "tagma_wasm_bg.wasm");
const outPath = join(here, "..", "src", "inline.mjs");

const bytes = readFileSync(wasmPath);
const base64 = bytes.toString("base64");

const banner = [
  "// GENERATED by scripts/inline.mjs from wasm/web/tagma_wasm_bg.wasm.",
  "// Do not edit by hand — regenerate via `just build-wasm`.",
].join("\n");

const source = `${banner}
import { initSync, Index, compile, parseTag } from "../wasm/web/tagma_wasm.js";

const WASM_BASE64 = "${base64}";

function decodeBase64(base64) {
  if (typeof Buffer !== "undefined") {
    return new Uint8Array(Buffer.from(base64, "base64"));
  }
  const binary = atob(base64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    out[i] = binary.charCodeAt(i);
  }
  return out;
}

initSync({ module: decodeBase64(WASM_BASE64) });

export { Index, compile, parseTag };
`;

writeFileSync(outPath, source);
console.log(
  `inline.mjs: embedded ${bytes.length} bytes as base64 (${base64.length} chars) -> ${outPath}`,
);
