#ifndef TAGMA_H
#define TAGMA_H

/* Generated by cbindgen. Do not edit by hand — see crates/tagma-ffi/cbindgen.toml and `just build-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Creates a new, empty index and returns an opaque owning handle to it.
 * The caller must eventually pass the handle to [`tagma_index_free`].
 */
void *tagma_index_new(void);

/**
 * Frees an index handle previously returned by [`tagma_index_new`]. A null
 * handle is a no-op.
 *
 * # Safety
 *
 * `handle`, if non-null, must be a still-live pointer previously returned
 * by [`tagma_index_new`], not already freed, and not used again after this
 * call.
 */
void tagma_index_free(void *handle);

/**
 * Parses and adds a `<id> <tag> <tag>...` line to the index (same line
 * format as `tagma-cli query`'s stdin). Returns `0` on success, `-1` on
 * error (see [`tagma_last_error`]).
 *
 * # Safety
 *
 * `handle` must be a live pointer from [`tagma_index_new`]. `line`, if
 * non-null, must point to a valid NUL-terminated UTF-8 C string.
 */
int tagma_index_add(void *handle, const char *line);

/**
 * Compiles `q` (infix) and evaluates it against the index, returning a
 * newly allocated, newline-joined, sorted list of matching ids (empty
 * string for no matches). Returns `NULL` on error (see
 * [`tagma_last_error`]); free the result with [`tagma_str_free`].
 *
 * # Safety
 *
 * `handle` must be a live pointer from [`tagma_index_new`]. `q`, if
 * non-null, must point to a valid NUL-terminated UTF-8 C string.
 */
char *tagma_query(void *handle, const char *q);

/**
 * Evaluates an already-compiled postfix query against the index; same
 * return convention as [`tagma_query`].
 *
 * # Safety
 *
 * `handle` must be a live pointer from [`tagma_index_new`]. `q`, if
 * non-null, must point to a valid NUL-terminated UTF-8 C string.
 */
char *tagma_query_postfix(void *handle, const char *q);

/**
 * Compiles an infix query `q` to its canonical postfix form. Returns
 * `NULL` on error (see [`tagma_last_error`]); free the result with
 * [`tagma_str_free`].
 *
 * # Safety
 *
 * `q`, if non-null, must point to a valid NUL-terminated UTF-8 C string.
 */
char *tagma_compile(const char *q);

/**
 * Returns a newly allocated copy of the last error message recorded on
 * this thread, or `NULL` if there is none. Free the result with
 * [`tagma_str_free`].
 */
char *tagma_last_error(void);

/**
 * Frees a string previously returned by [`tagma_query`],
 * [`tagma_query_postfix`], [`tagma_compile`], or [`tagma_last_error`]. A
 * null pointer is a no-op.
 *
 * # Safety
 *
 * `s`, if non-null, must be a still-live pointer previously returned by
 * one of this crate's string-returning functions, not already freed, and
 * not used again after this call.
 */
void tagma_str_free(char *s);

#endif  /* TAGMA_H */
