/* tagma C ABI.
 *
 * Panic safety
 * ------------
 * No function declared here can unwind a Rust panic into your frames, and
 * none of them can abort your process because of one. Every entry point
 * catches a panic at the boundary and reports it as an ordinary failure:
 * -1 for the int-returning functions, NULL for the pointer-returning ones,
 * with a message retrievable from tagma_last_error() prefixed
 * `ffi: panic in <function>:`.
 *
 * Invalid input is a defined error, not a panic and not undefined
 * behaviour. A null string pointer, an invalid index handle, bytes that are
 * not valid UTF-8, and a malformed query all take the normal error return;
 * the caught-panic path exists only as a backstop for genuine bugs in tagma
 * or in a client-supplied extension.
 *
 * Index handles
 * -------------
 * TagmaIndex is an opaque token, NOT a pointer: do not dereference it, do
 * not cast a pointer to it, do not assume any structure. 0 is never a valid
 * handle and is what tagma_index_new() returns on failure.
 *
 * Every handle is validated on entry, so the classic C lifetime mistakes
 * are reported instead of being undefined behaviour. Freeing a handle
 * twice, using one after freeing it, and passing a value tagma never issued
 * each return the function's ordinary failure value (-1, or NULL) with a
 * message in tagma_last_error(). A freed handle is never reissued for a
 * later index, so a stale handle can never be silently redirected to an
 * unrelated one. tagma_index_free() returns int for this reason: 0 on
 * success, -1 if the handle was not live. Freeing handle 0 is a no-op
 * returning 0, like free(NULL).
 *
 * Handles are thread-safe. Any function here may be called from any thread,
 * with the same handle or different ones, without external locking;
 * operations on one index serialize, operations on different indexes run
 * concurrently. Freeing a handle another thread is still using is defined:
 * the handle dies immediately and the storage is released once the
 * in-flight call returns. (The error message from tagma_last_error() is
 * per-thread, as before.)
 *
 * String pointers are a separate matter and remain the caller's
 * responsibility: passing tagma_str_free() a pointer that is dangling,
 * already freed, or not one tagma returned is still undefined behaviour.
 *
 * Extensions must not panic. A future client-registered type comparator
 * (SPEC.md section 9) that panics is a contract violation on the client's
 * side; tagma will contain the unwind and turn it into an error return here
 * rather than corrupt the stack, but it may leave the operation's result
 * unspecified. Report errors through the documented return values instead.
 */


#ifndef TAGMA_H
#define TAGMA_H

/* Generated by cbindgen. Do not edit by hand — see crates/tagma-ffi/cbindgen.toml and `just build-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The integer handle type exposed to C. Opaque: callers must treat it as a
 * token, never as an address or an index. `0` is never a valid handle.
 */
typedef uint64_t TagmaIndex;

/**
 * Creates a new, empty index and returns an opaque owning handle to it.
 * The caller must eventually pass the handle to [`tagma_index_free`].
 * Returns `0` if construction fails (see [`tagma_last_error`]); `0` is
 * never a valid handle. Never unwinds.
 */
TagmaIndex tagma_index_new(void);

/**
 * Frees the index named by a handle previously returned by
 * [`tagma_index_new`]. Returns `0` on success and `-1` if the handle is
 * not a live tagma handle — already freed, never issued, or garbage — with
 * the reason in [`tagma_last_error`]. A `0` handle is a no-op returning
 * `0`, mirroring `free(NULL)`.
 *
 * After a successful call the handle is dead: every later use of it,
 * including another free, is a defined error rather than undefined
 * behaviour, and it will never be reissued for a future index.
 *
 * Never unwinds: a panic while dropping the index is caught and recorded
 * for [`tagma_last_error`].
 */
int tagma_index_free(TagmaIndex handle);

/**
 * Parses and adds a `<id> <tag> <tag>...` line to the index (same line
 * format as `tagma-cli query`'s stdin). Returns `0` on success, `-1` on
 * error (see [`tagma_last_error`]).
 *
 * # Safety
 *
 * `line`, if non-null, must point to a valid NUL-terminated UTF-8 C
 * string. `handle` needs no precondition: an invalid one is a reported
 * error.
 */
int tagma_index_add(TagmaIndex handle, const char *line);

/**
 * Compiles `q` (infix) and evaluates it against the index, returning a
 * newly allocated, newline-joined, sorted list of matching ids (empty
 * string for no matches). Returns `NULL` on error (see
 * [`tagma_last_error`]); free the result with [`tagma_str_free`].
 *
 * # Safety
 *
 * `q`, if non-null, must point to a valid NUL-terminated UTF-8 C string.
 * `handle` needs no precondition: an invalid one is a reported error.
 */
char *tagma_query(TagmaIndex handle, const char *q);

/**
 * Evaluates an already-compiled postfix query against the index; same
 * return convention as [`tagma_query`].
 *
 * # Safety
 *
 * `q`, if non-null, must point to a valid NUL-terminated UTF-8 C string.
 * `handle` needs no precondition: an invalid one is a reported error.
 */
char *tagma_query_postfix(TagmaIndex handle, const char *q);

/**
 * Compiles an infix query `q` to its canonical postfix form. Returns
 * `NULL` on error (see [`tagma_last_error`]); free the result with
 * [`tagma_str_free`].
 *
 * # Safety
 *
 * `q`, if non-null, must point to a valid NUL-terminated UTF-8 C string.
 */
char *tagma_compile(const char *q);

/**
 * Returns a newly allocated copy of the last error message recorded on
 * this thread, or `NULL` if there is none. Free the result with
 * [`tagma_str_free`]. Never unwinds.
 *
 * A caught panic from any other entry point is reported through this same
 * channel, prefixed `ffi: panic in <function>:`.
 */
char *tagma_last_error(void);

/**
 * Frees a string previously returned by [`tagma_query`],
 * [`tagma_query_postfix`], [`tagma_compile`], or [`tagma_last_error`]. A
 * null pointer is a no-op.
 *
 * # Safety
 *
 * `s`, if non-null, must be a still-live pointer previously returned by
 * one of this crate's string-returning functions, not already freed, and
 * not used again after this call.
 *
 * Never unwinds.
 */
void tagma_str_free(char *s);

#endif  /* TAGMA_H */
